env:
  es6: true,
  jquery: true
  browser: true,
extends: airbnb-base
globals:
  window: true
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: 
  no-console: 0
  max-len:
    - 2
    - 192
